# Generated by Django 3.2.3 on 2022-04-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('fee', models.CharField(max_length=100)),
                ('coordinator_name', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('Sabrang 2018', 'Sabrang 2018'), ('Sabrang 2019', 'Sabrang 2019'), ('Sabrang 2022', 'Sabrang 2022')], default=3, max_length=30)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
