# Generated by Django 3.2.3 on 2022-04-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prize',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.CharField(choices=[('Sabrang 2018', 'Sabrang 2018'), ('Sabrang 2019', 'Sabrang 2019'), ('Sabrang 2022', 'Sabrang 2022')], default=1, max_length=30),
        ),
    ]
