# Generated by Django 3.2.3 on 2022-04-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_auto_20220420_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coordinator_no',
            field=models.CharField(default='', max_length=100),
        ),
    ]
