# Generated by Django 3.2.3 on 2022-04-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_event_coordinator_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourteam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('post', models.CharField(choices=[('Dignitaries', 'Dignitaries'), ('Organizing Committee', 'Organizing Committee'), ('Core Committee', 'Core Committee')], default=1, max_length=30)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='coordinator_no',
            field=models.CharField(default='', max_length=10),
        ),
    ]
