# Generated by Django 3.2.3 on 2022-04-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_auto_20220424_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourteam',
            name='post',
        ),
        migrations.RemoveField(
            model_name='ourteam',
            name='title',
        ),
        migrations.AddField(
            model_name='ourteam',
            name='sponsorstype',
            field=models.CharField(choices=[('Gold Sponsor', 'Gold Sponsor'), ('Event Sponsors', 'Event Sponsors'), ('Stall Sponsors', 'Stall Sponsors'), ('Printing Partner', 'Printing Partner')], default=1, max_length=30),
        ),
    ]
