# Generated by Django 3.2.3 on 2022-04-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_auto_20220424_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sponsorstype', models.CharField(choices=[('Gold Sponsor', 'Gold Sponsor'), ('Event Sponsors', 'Event Sponsors'), ('Stall Sponsors', 'Stall Sponsors'), ('Printing Partner', 'Printing Partner')], default=1, max_length=30)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
