# Generated by Django 4.0.4 on 2022-04-25 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_participants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participants',
            new_name='Participant',
        ),
    ]
