# Generated by Django 4.0.4 on 2022-05-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0010_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='club_name',
            field=models.CharField(choices=[('Drama Club', 'Drama Club'), ('Dance Club', 'Dance Club'), ('Business & Finance Club', 'Business & Finance Club'), ('Robotics Club', 'Robotics Club'), ('Music Club', 'Music Club'), ('Quiz Club', 'Quiz Club')], default='Drama Club', max_length=30),
        ),
    ]
